spring:
    main:
        show_banner: off
    application:
        name: com.simple.fb.app
    profiles:
        active: dev
    session:
        store-type: none
#    social:
#        facebook:
#            appId: 384261248599251
#            appSecret: fd7fa1c5f5a267f463263a0ce7ff2025
#    #CSCFirstApp for account nikitazogascsc@gmail.com
#       app-id: 625813347760256
#       app-secret: a53ae62be648b8a78e6892958440a3f8
#       client-token: 1c9ed458c0ce7fc0958d27ec817497da
    facebook:
        client:
            clientId: 233668646673605
            clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
        resource:
            userInfoUri: https://graph.facebook.com/me

---

spring.profiles: dev

server:
    #port: 8802
    port: 8080
    #port: 3000

---

spring.profiles: test

server:
    port: 8801

---

spring.profiles: prod

server:
    port: 8800