spring:
    application:
        name: com.simple.social.app
    profiles:
        active: dev
    session:
        store-type: none
    google:
        client:
            clientId: 337933304404-uav04294ppeagcqnhkrbr2g88t5ndrcv.apps.googleusercontent.com
            clientSecret: 73DgkxIUtFhmvB1uLFGlOh0R
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: 
                - openid
                - email
                - profile
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false
            issuer: accounts.google.com
            jwkUrl: https://www.googleapis.com/oauth2/v2/certs
    facebook:
        client:
            appId: 625813347760256
            appSecret: a53ae62be648b8a78e6892958440a3f8
            appAccessToken: 1c9ed458c0ce7fc0958d27ec817497da
            accessTokenUri: https://graph.facebook.com/v2.12/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/v2.12/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope:
                - email
                - public_profile
        resource:
            userInfoUri: https://graph.facebook.com/v2.12/me

---

spring.profiles: dev

server:
    port: 8802
google:
    resource:
        redirectUri: http://localhost:8802/google/login
facebook:
    resource:
        redirectUri: http://localhost:8801/facebook/login

---

spring.profiles: test

server:
    port: 8801
google:
    resource:
        redirectUri: http://localhost:8801/google/login
facebook:
    resource:
        redirectUri: http://localhost:8801/facebook/login

---

spring.profiles: prod

server:
    port: 8800
google:
    resource:
        redirectUri: https://springboot-social-login-app-87.herokuapp.com/google/login
facebook:
    resource:
        redirectUri: https://springboot-social-login-app-87.herokuapp.com/facebook/login
