spring:
    application:
        name: com.simple.social.app
    profiles:
        active: prod
    session:
        store-type: none
    google:
        client:
            clientId: 337933304404-uav04294ppeagcqnhkrbr2g88t5ndrcv.apps.googleusercontent.com
            clientSecret: 73DgkxIUtFhmvB1uLFGlOh0R
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: profile
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false
            issuer: accounts.google.com
            jwkUrl: https://www.googleapis.com/oauth2/v2/certs

---

spring.profiles: dev

server:
    port: 8802
google:
    resource:
        redirectUri: http://localhost:8802/googlelogin

---

spring.profiles: test

server:
    port: 8801
google:
    resource:
        redirectUri: http://localhost:8801/googlelogin

---

spring.profiles: prod

server:
    port: 8800
google:
    resource:
        redirectUri: http://localhost:8800/googlelogin
